### ISSUE TITLE
Wrong flag to start the plugin

### ISSUE THREAD

**Issue by maniac-semal** [ich777/unraid-prometheus_pihole_exporter#2]
The plugin was no longer working for me and after trying and checking the scripts I found the issue in the:

- [prometheus_pihole_exporter_init.sh](https://github.com/ich777/unraid-prometheus_pihole_exporter/blob/master/source/usr/local/emhttp/plugins/prometheus_pihole_exporter/include/prometheus_pihole_exporter_init.sh)
- [prometheus_pihole_exporter_start.sh](https://github.com/ich777/unraid-prometheus_pihole_exporter/blob/master/source/usr/local/emhttp/plugins/prometheus_pihole_exporter/include/prometheus_pihole_exporter_start.sh)

It seems the update to 0.3.0 changed the flag for "interval" to "timeout" (for whatever reason...). Therefore the plugin does not start. 

`prometheus_pihole_exporter -pihole_api_token $2 -pihole_hostname $1 -pihole_protocol $3 -pihole_port $4 -port $5 -interval $6s`

needs to be

`prometheus_pihole_exporter -pihole_api_token $2 -pihole_hostname $1 -pihole_protocol $3 -pihole_port $4 -port $5 -timeout $6s`

I made a temporary fix for myself which will be gone again after the next restart of my server. Could you check and verify/correct this?

**Comment by ich777** [comment]
Thank you for the report, please update the plugin, should be fixed now. :)
